#!/bin/bash
ROOT_PATH=%ROOT%
MEMBERS_LIST=$ROOT_PATH/members-list
SCORE_FILE=$ROOT_PATH/scores
SETUP_SCRIPT=$ROOT_PATH/setup-system
GLOBAL_VARS=$ROOT_PATH/global-paths.sh
GENERATE_MEMBERS_SCRIPT=$ROOT_PATH/generate-members
DISPLAY_SCORES_SCRIPT=$ROOT_PATH/display-points
GET_SCORE_SCRIPT=$ROOT_PATH/get-member-score
GIVE_PTS_SCRIPT=$ROOT_PATH/give-points.sh
GIVE_PTS_EXEC=$ROOT_PATH/give-points
GIVE_PTS_SRC=$ROOT_PATH/give-points-outer.c
GIVE_PRIZES_SCRIPT=$ROOT_PATH/give-out-prizes
FILES_LIST="$MEMBERS_LIST $SCORE_FILE $SETUP_SCRIPT $GLOBAL_VARS $GENERATE_MEMBERS_SCRIPT $DISPLAY_SCORES_SCRIPT $GET_SCORE_SCRIPT $GIVE_PTS_SCRIPT $GIVE_PRIZES_SCRIPT $GIVE_PTS_EXEC $GIVE_PTS_SRC"
BASE_SCORE="10"
ADMIN_BASE_SCORE="10000"
